In [46]:
import numpy as np

In [47]:
# ----------------------Arithmetic Operations----------------------

In [48]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])
a1, a2

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [49]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [50]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [51]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [52]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [53]:
a1 % a2 == 2

array([False,  True, False, False, False])

In [54]:
a1 // a2

array([0, 0, 0, 0, 0])

In [55]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [56]:
# ----------------------Broadcasting----------------------

In [57]:
l = [15, 25, 35, 45, 55]
arr = np.array(l)
arr

array([15, 25, 35, 45, 55])

In [58]:
arr + 10

array([25, 35, 45, 55, 65])

In [59]:
arr2 = np.arange(1, 31).reshape(6, 5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [60]:
arr2 + 5

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [61]:
arr2 * 3

array([[ 3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30],
       [33, 36, 39, 42, 45],
       [48, 51, 54, 57, 60],
       [63, 66, 69, 72, 75],
       [78, 81, 84, 87, 90]])

In [62]:
arr2 - 5

array([[-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [63]:
arr2 % 2 == 0

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [64]:
arr2 ** 5

array([[       1,       32,      243,     1024,     3125],
       [    7776,    16807,    32768,    59049,   100000],
       [  161051,   248832,   371293,   537824,   759375],
       [ 1048576,  1419857,  1889568,  2476099,  3200000],
       [ 4084101,  5153632,  6436343,  7962624,  9765625],
       [11881376, 14348907, 17210368, 20511149, 24300000]])

In [65]:
# ----------------------Deep and shallow copy----------------------

In [66]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [67]:
slice = a[:7]
slice * 9

array([ 9, 18, 27, 36, 45, 54, 63])

In [68]:
b = a.copy()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [69]:
b[5] = 100
b

array([  1,   2,   3,   4,   5, 100,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [70]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [71]:
# ----------------------Matrix Operations----------------------

In [88]:
A = np.array([[1, 3], [7, 9]])
B = np.array([[2, 4], [6, 8]])

In [89]:
A

array([[1, 3],
       [7, 9]])

In [90]:
B

array([[2, 4],
       [6, 8]])

In [91]:
A @ B # Matrix multiplication

array([[ 20,  28],
       [ 68, 100]])

In [92]:
np.dot(A, B)

array([[ 20,  28],
       [ 68, 100]])

In [93]:
A.T  # Transpose

array([[1, 7],
       [3, 9]])

In [ ]:
# ----------------------Advanced Array Manipulation----------------------

In [ ]:
# Stacking Array

In [97]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [98]:
np.vstack((a, b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [99]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [100]:
np.column_stack((a, b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
# Splitting Array

In [102]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [109]:
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [110]:
np.vsplit(c, 4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]