In [1]:
import numpy as np

In [ ]:
# ----------------------Numpy Indexing and Slicing of vectors----------------------

In [2]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[5]

np.int64(16)

In [4]:
arr[1:5]

array([12, 13, 14, 15])

In [5]:
arr[3::2]

array([14, 16, 18, 20])

In [6]:
# ----------------------Numpy Indexing and Slicing of Matrix----------------------

In [7]:
arr = np.arange(1, 31).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [8]:
arr[3], arr[5], arr[1]

(array([16, 17, 18, 19, 20]),
 array([26, 27, 28, 29, 30]),
 array([ 6,  7,  8,  9, 10]))

In [9]:
arr[0,4], arr[5,4]

(np.int64(5), np.int64(30))

In [10]:
arr[0:2, 1:3]

array([[2, 3],
       [7, 8]])

In [11]:
arr[3:5, 3:4]

array([[19],
       [24]])

In [12]:
arr[3:, 2:]

array([[18, 19, 20],
       [23, 24, 25],
       [28, 29, 30]])

In [13]:
arr[:, 3]

array([ 4,  9, 14, 19, 24, 29])

In [14]:
# ----------------------Boolean Indexing----------------------

In [21]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
bool = arr % 2 == 0
bool

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [23]:
arr = arr[bool]
arr

array([12, 14, 16, 18, 20])