In [3]:
import numpy as np

In [4]:
# ----------------------Basic Array Creation----------------------

In [5]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [6]:
a = [1, 2, 'hell']
np.array(a)

array(['1', '2', 'hell'], dtype='<U21')

In [7]:
b = [[1, 2, 3], [4, 5, 6]]
np.array(b)

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# ----------------------Array Generation Function----------------------

In [9]:
c = np.arange(1, 11, 2)
c

array([1, 3, 5, 7, 9])

In [10]:
arr = np.zeros((4, 5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
arr = np.ones((4, 4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
arr = np.linspace(0, 1, 150)
arr

array([0.        , 0.00671141, 0.01342282, 0.02013423, 0.02684564,
       0.03355705, 0.04026846, 0.04697987, 0.05369128, 0.06040268,
       0.06711409, 0.0738255 , 0.08053691, 0.08724832, 0.09395973,
       0.10067114, 0.10738255, 0.11409396, 0.12080537, 0.12751678,
       0.13422819, 0.1409396 , 0.14765101, 0.15436242, 0.16107383,
       0.16778523, 0.17449664, 0.18120805, 0.18791946, 0.19463087,
       0.20134228, 0.20805369, 0.2147651 , 0.22147651, 0.22818792,
       0.23489933, 0.24161074, 0.24832215, 0.25503356, 0.26174497,
       0.26845638, 0.27516779, 0.28187919, 0.2885906 , 0.29530201,
       0.30201342, 0.30872483, 0.31543624, 0.32214765, 0.32885906,
       0.33557047, 0.34228188, 0.34899329, 0.3557047 , 0.36241611,
       0.36912752, 0.37583893, 0.38255034, 0.38926174, 0.39597315,
       0.40268456, 0.40939597, 0.41610738, 0.42281879, 0.4295302 ,
       0.43624161, 0.44295302, 0.44966443, 0.45637584, 0.46308725,
       0.46979866, 0.47651007, 0.48322148, 0.48993289, 0.49664

In [13]:
# ----------------------Random Generation Function----------------------

In [14]:
np.random.rand(20)

array([0.42184545, 0.68544517, 0.93523966, 0.27135233, 0.65718999,
       0.83903275, 0.41189284, 0.22962802, 0.34130555, 0.31998324,
       0.45698549, 0.80728824, 0.37704243, 0.04543798, 0.57847377,
       0.76927805, 0.91188327, 0.22803965, 0.86939948, 0.18271077])

In [15]:
np.random.randn(100)

array([-0.0695405 ,  2.07122123, -0.53222394, -0.41457072,  1.22619826,
       -0.58128936, -0.72604859,  0.79598269,  1.4735522 , -2.7005432 ,
        1.9034891 , -0.44723506,  0.10779076,  1.07943193, -0.9146925 ,
        0.89261384,  0.05721714, -0.26143328, -0.08346656, -2.11782632,
        1.57396148, -1.69183608,  0.35456105,  1.18372835, -0.15314201,
        1.20764691, -1.81216926, -1.16819543,  0.54411672, -2.52829632,
        1.48709245, -1.58031796,  1.81023487, -1.04987126,  0.32973086,
       -0.25130219, -0.7333996 , -0.45172702,  0.10433151,  0.65601277,
       -1.18799148, -0.78122665, -0.91997757,  1.80625653,  0.28586147,
       -0.17573867,  0.17157014,  0.67964753,  0.65355933,  0.30378206,
       -0.09081803,  0.9617332 ,  1.41524451,  0.01688948,  1.96684661,
       -0.1571179 , -0.94820489,  1.19384954,  0.40044468,  0.91385155,
       -1.75416738, -0.04839648, -0.20638051,  0.62320149,  1.23328105,
       -0.29755129,  0.86322325, -1.71220604, -0.1107021 ,  0.32

In [16]:
np.random.randint(0, 10, 25)

array([1, 8, 6, 0, 3, 8, 1, 5, 2, 4, 5, 3, 1, 3, 2, 5, 2, 5, 2, 9, 2, 9,
       8, 1, 5])

In [17]:
#Array Attributes

In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr.shape

(3, 3)

In [20]:
arr.size

9

In [21]:
arr.dtype

dtype('int64')

In [22]:
# ----------------------Array Methods----------------------

In [23]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr.min()

np.int64(1)

In [25]:
arr.max()

np.int64(9)

In [26]:
arr.sum()

np.int64(45)

In [27]:
np.sum(arr, axis = 0)  #Summation of columns

array([12, 15, 18])

In [28]:
np.sum(arr, axis = 1)  #Summation of rows

array([ 6, 15, 24])

In [29]:
arr.mean()

np.float64(5.0)

In [30]:
arr.std()

np.float64(2.581988897471611)

In [31]:
arr.argmax()

np.int64(8)

In [32]:
arr.argmin()

np.int64(0)

In [33]:
# ----------------------Reshaping and resizing----------------------

In [34]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [35]:
arr = arr.reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [37]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])